insert into games (name) values
('Minecraft'),
('FIFA 24'),
('Call of Duty'),
('Free Fire'),
('Fortnite'),
('Ludo'),
('Chess'),
('Monopoly'),
('Uno');
('Among Us'),
('Clash of Clans'),
('PUBG Mobile'),
('Roblox'),
('Asphalt 9'),
('Candy Crush Saga'),
('Subway Surfers'),
('Temple Run'),
('Angry Birds'),
('Pokémon GO'),
('Genshin Impact');
('Valorant'),
('Apex Legends'),
('Rocket League'),
('The Sims 4'),
('League of Legends'),
('Dota 2'),
('World of Warcraft'),
('Overwatch'),
('Hearthstone'),
('StarCraft II');
('Animal Crossing: New Horizons'),
('Cyberpunk 2077'),
('Elden Ring'),
('God of War'),
('Horizon Zero Dawn'),
('Red Dead Redemption 2'),
('The Witcher 3: Wild Hunt'),
('Assassin s Creed Valhalla'),
('Death Stranding'),
('Ghost of Tsushima'),
('Final Fantasy VII Remake');
('Minecraft Dungeons'),
('Terraria'),
('Stardew Valley'),
('Dont Starve'),
('Factorio'),
('RimWorld'),
('The Binding of Isaac'),
('Hades'),
('Celeste'),
('Hollow Knight'),
('Cuphead');
('Dark Souls III'),
('Sekiro: Shadows Die Twice'),
('Bloodborne'),
('Nioh 2'),
('Monster Hunter: World'),
('Dragon Age: Inquisition'),
('Mass Effect: Andromeda'),
('Divinity: Original Sin 2'),
('Pillars of Eternity II: Deadfire'),
('Baldur s Gate 3'),
('Tales of Arise');
('Farming Simulator 19'),   
('Euro Truck Simulator 2'),
('The Crew 2'),
('Forza Horizon 5'),
('Gran Turismo Sport'),
('Need for Speed Heat'),
('Project CARS 3'),
('Dirt 5'),
('Assetto Corsa Competizione'),
('WRC 10'),
('F1 2021');
('Valorant'),
('Apex Legends'),
('Rocket League'),
('The Sims 4'),
('League of Legends'),
('Dota 2'),
('World of Warcraft'),
('Overwatch'),
('Hearthstone'),
('StarCraft II');
('Animal Crossing: New Horizons'),
('Cyberpunk 2077'),
('Elden Ring'),
('God of War'),
('Horizon Zero Dawn'),
('Red Dead Redemption 2'),
('The Witcher 3: Wild Hunt'),
('Assassin s Creed Valhalla'),
('Death Stranding'),
('Ghost of Tsushima'),
('Final Fantasy VII Remake');
('Minecraft Dungeons'),
('Terraria'),
('Stardew Valley'),
('Dont Starve'),
('Factorio'),
('RimWorld'),
('The Binding of Isaac'),
('Hades'),
('Celeste'),
('Hollow Knight'),
('Cuphead');
('Dark Souls III'),
('Sekiro: Shadows Die Twice'),
('Bloodborne'),
('Nioh 2'),
('Monster Hunter: World'),
('Dragon Age: Inquisition'),
('Mass Effect: Andromeda'),
('Divinity: Original Sin 2'),
('Pillars of Eternity II: Deadfire'),
('Baldur s Gate 3'),
('Tales of Arise');
('Farming Simulator 19'),   
('Euro Truck Simulator 2'),
('The Crew 2'),
('Forza Horizon 5'),
('Gran Turismo Sport'),
('Need for Speed Heat'),
('Project CARS 3'),
('Dirt 5'),
('Assetto Corsa Competizione'),
('WRC 10'),
('F1 2021');